version: 2
updates:
- package-ecosystem: gradle
  directory: "/jbake-core"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/jbake-dist"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
